version: '3.7'

services:
  tchat: 
    build: 
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tchat
    container_name: tchat
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: /start
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: db-tchat
    env_file:
      - ./.env
    ports:
      - "5432:5432"
